[project]
name = "wagtailstreaming"
description = "A Wagtail module for segmenting videos and serving stream manifests"
authors = [
    {name = "Felix Leo Flores", email = "floresfelixleo.fleurs96@gmail.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = [
    "Wagtail", "Django", 
    "HLS", "MPEG-DASH", "FFmpeg", 
    "Video", "Streaming"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Wagtail",
    "Framework :: Wagtail :: 6",
    "Framework :: Wagtail :: 7",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12", 
    "Programming Language :: Python :: 3.13", 
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Multimedia :: Video",
]
requires-python = ">=3.9"
dynamic = ["version", "dependencies"]

[project.urls]
Repository = "https://github.com/scibizinformatics/wagtail-streaming"
Issues = "https://github.com/scibizinformatics/wagtail-streaming/issues"

[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
exclude = [
    "build", "dist", 
    "docs", "tests*", "test*",  
    ".github", "dev", 
    "postgres-data",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.dynamic]
version = { attr = "wagtailstreaming.__version__" }
dependencies = { file = ["requirements.txt"] }