# Generated by Django 5.2.7 on 2025-10-30 17:58

import django.db.models.deletion
import taggit.managers
import wagtail.models.media
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0094_alter_page_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='the title of the video', max_length=255, unique=True, verbose_name='title')),
                ('file', models.FileField(blank=True, help_text='the video that is going to be processed or that has been processed, video must be lower or equal to 100MB', null=True, upload_to='videos', verbose_name='file')),
                ('file_url', models.URLField(blank=True, help_text='the link that contains the video when video is greater than 100MB', max_length=255, null=True, verbose_name='file URL')),
                ('thumbnail', models.FileField(blank=True, help_text='the thumbail of the video', null=True, upload_to='media_thumbnails', verbose_name='thumbnail')),
                ('process_id', models.IntegerField(blank=True, help_text='the process id where the video is being processed', null=True, verbose_name='process ID')),
                ('hls_ready', models.BooleanField(default=False, help_text='marked if the raw video has been converted to HLS format', verbose_name='has HLS format')),
                ('dash_ready', models.BooleanField(default=False, help_text='marked if the raw video has been converted to MPEG-DASH format', verbose_name='has MPEG-DASH format')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='the date in which the video has been uploaded', verbose_name='created at')),
                ('date_processed', models.DateTimeField(blank=True, help_text='the date in which the video has started its conversion to HLS or DASH format', null=True, verbose_name='start of conversion')),
                ('date_finished', models.DateTimeField(blank=True, help_text='the date in which the video was done converting', null=True, verbose_name='conversion finished at')),
                ('remarks', models.TextField(blank=True, help_text='message logs or audit logs related to the video', null=True, verbose_name='remarks')),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='tags that relates to the video, separate each tag via commas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, help_text='the user that uploaded the video', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'video stream',
                'ordering': ['title'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
