# Generated by Django 5.2.7 on 2026-03-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailstreaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostream',
            name='audio_ready',
            field=models.BooleanField(default=False, help_text='marked if the audio of the video has been extracted', verbose_name='has an audio file'),
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Language name assigned to this transcription', max_length=32)),
                ('language', models.CharField(help_text='Language code assigned to this transcription', max_length=16)),
                ('slug', models.SlugField(help_text='Filesystem-safe identifier', max_length=32)),
                ('default', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='wagtailstreaming.videostream')),
            ],
            options={
                'verbose_name': 'transcript',
                'ordering': ['video', 'language', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DurationField(help_text='The start range of the text when it is heard in the video')),
                ('end', models.DurationField(help_text='The end range of the text when it is heard in the video')),
                ('text', models.TextField(help_text='The text for this transcription')),
                ('synced', models.BooleanField(default=False, help_text='Marked if transcript has not been synced to corresponding .vtt file yet')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cues', to='wagtailstreaming.transcript')),
            ],
            options={
                'verbose_name': 'transcript cue',
                'ordering': ['transcript', 'start'],
            },
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(fields=('video', 'language', 'name', 'slug'), name='unique_transcript_per_video_language_name_slug'),
        ),
        migrations.AddConstraint(
            model_name='transcript',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True)), fields=('video',), name='unique_default_transcript_per_video'),
        ),
    ]
